version: '3.1'
services:
  app:
    container_name: Task13
    image: springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "5432-5432"
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DB=memory
